// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0jnqJ4YliLI5Vh-AUaUp2-ep2kcE9vw',
    appId: '1:301913921667:web:92cc16b72a44462bb3a3b6',
    messagingSenderId: '301913921667',
    projectId: 'finpal-81b7e',
    authDomain: 'finpal-81b7e.firebaseapp.com',
    storageBucket: 'finpal-81b7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqnr8ddvhe6NIXu5aE4uY8K8Su79mKmJ0',
    appId: '1:301913921667:android:b0adb2ab55292d8cb3a3b6',
    messagingSenderId: '301913921667',
    projectId: 'finpal-81b7e',
    storageBucket: 'finpal-81b7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_2wcTRRhvNcwOKZke0T_06kcQSFTl2iE',
    appId: '1:301913921667:ios:84ebf1505d74ed5cb3a3b6',
    messagingSenderId: '301913921667',
    projectId: 'finpal-81b7e',
    storageBucket: 'finpal-81b7e.appspot.com',
    iosBundleId: 'com.example.finpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_2wcTRRhvNcwOKZke0T_06kcQSFTl2iE',
    appId: '1:301913921667:ios:14259c844f86ba8bb3a3b6',
    messagingSenderId: '301913921667',
    projectId: 'finpal-81b7e',
    storageBucket: 'finpal-81b7e.appspot.com',
    iosBundleId: 'com.example.finpal.RunnerTests',
  );
}
